apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: playeconomy-host
spec:
  hostname: playeconomy-gateway.westus2.cloudapp.azure.com
  acmeProvider:
    email: officialgio121@gmail.com
  tlsSecret: 
    name: playeconomy-tls