apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: identity-mapping
spec: 
  hostname: playeconomy-gateway.westus2.cloudapp.azure.com
  prefix: /identity/svc/
  service: identity-service.identity