apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: playeconomy-tls-cert
spec:
  secretName: playeconomy-tls # the actual keys
  issuerRef:
    name: letsencrypt-pod # refers to this ClusterIssuer
    kind: ClusterIssuer
  dnsNames: 
    - "playeconomy-gateway.westus2.cloudapp.azure.com"