{{- if .Values.certificate}} # deploy only if the cert is defined
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{.Values.microserviceName}}-cert"
spec:
  secretName: {{.Values.certificate.secretName}}
  # the issuer remains to provision the new cert
  issuerRef:
    name: letsencrypt-pod # refers to the ClusterIssuer
    kind: ClusterIssuer
  dnsNames:
    - {{.Values.certificate.hostname}}
{{- end}}