apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.microserviceName}}-service"
spec:
  type: {{.Values.service.type}} # Local within cluster but not externally public
  selector:
    app: {{.Values.microserviceName}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.container.port}}
