apiVersion: v1
kind: Service
metadata:
  name: acme-challenge-service
spec:
  ports:
    - protocol: TCP
      port: 80 # receive on this port 
      targetPort: 8089 # forwarding to the temp pod port
  selector:
    acme.cert-manager.io/http01-solver: "true" # temp pod must match this
  
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: acme-challenge-mapping
spec:
  hostname: playeconomy-gateway.westus2.cloudapp.azure.com
  prefix: /.well-known/acme-challenge/
  rewrite: ""
  service: acme-challenge-service